name: base
channels:
  - defaults
dependencies:
  - boltons=23.0.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - conda=23.9.0
  - conda-content-trust=0.1.3
  - conda-libmamba-solver=23.9.1
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cryptography=39.0.1
  - fmt=9.1.0
  - icu=73.1
  - idna=3.4
  - jsonpatch=1.32
  - jsonpointer=2.1
  - krb5=1.20.1
  - libarchive=3.6.2
  - libcurl=8.4.0
  - libcxx=14.0.6
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libiconv=1.16
  - libmamba=1.5.1
  - libmambapy=1.5.1
  - libnghttp2=1.57.0
  - libsolv=0.7.24
  - libssh2=1.10.0
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - ncurses=6.4
  - openssl=3.0.11
  - packaging=23.1
  - pcre2=10.42
  - pip=23.1.2
  - pluggy=1.0.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.4
  - python.app=3
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - ruamel.yaml=0.17.21
  - setuptools=67.8.0
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tqdm=4.65.0
  - truststore=0.8.0
  - tzdata=2023c
  - urllib3=1.26.16
  - wheel=0.38.4
  - xz=5.4.2
  - yaml-cpp=0.7.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
